### ISSUE TITLE
[v4.8.1] McpTool isn't imported with type-only imports and fails for builds with verbatimModuleSyntax enabled

### ISSUE THREAD

**Issue by Q16solver** [Azure/azure-functions-nodejs-library#380]
Hi,

It seems like mcptooling are new things added from v4.8.0 -> v4.8.1, and broke some of my tooling in CI/CD (things like using typedoc to generate docs) with errors like
```
Args' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.

import { Args, McpToolProperty } from '../../types/mcpTool';
```

It would be great if we could turn that on and fix up the imports if it's not too much of a hassle, thanks!

**Comment by swapnil-nagar** [comment]
Thank you for notifying this issue

Created a PR for a fix. We will work on release

https://github.com/Azure/azure-functions-nodejs-library/pull/381

**Comment by Q16solver** [comment]
@swapnil-nagar Thanks for the quick reply! However, I don't think that's the only type with the issue, it might be best to turn **verbatimModuleSyntax** on in tsconfig.json, which should hopefully automatically notify all the imports that have this issue to convert to `import type {} from "foo"` syntax  and fix the root cause. This should also hopefully help a little with perf for typescript erasing all the `import type {}` lines

https://www.typescriptlang.org/tsconfig/#verbatimModuleSyntax

Edit: I noticed this is only for typescript v5, and typescript v4 doesn't have this yet, so may need to upgrade to latest typescript version, if this is too big of a change, perhaps it makes sense to have a separate typescript5 version like what seems to have been done for typescript4, and have a separate typechecking done to find issues, and migrate to single ver of typescript later for a major release

**Comment by swapnil-nagar** [comment]
Thanks for the information. We do plan to upgrade to TypeScript 5 and address the Undici deprecation in our next major release.

In the meantime, we’ve published version 4.8.2 which includes the fix mentioned here.

**Comment by Q16solver** [comment]
@swapnil-nagar  Ah, I mentioned the typescript upgrade because the fix mentioned here doesn't seem to fix the full issue, e.g. `McpToolProperty` also needs to be a type-only import. I think that should be all of it? but yeah, this would be mitigated in the next major release completely once the flag is enabled in tsconfig, but for now I suppose it'll just have to be manually checked

the errors reported in the CI/CD for reference: https://github.com/Esposter/Esposter/actions/runs/19084920840/job/54522877778#step:5:225

**Comment by swapnil-nagar** [comment]
Yes, I am waiting on Ignite(Nv 17-Nov18) to get over and after thanksgiving we will release the new version with the fix. For now I will close this issue.

**Comment by Q16solver** [comment]
I think this is still missing a small fix to convert from
`import { McpToolProperty } from '../../types/mcpTool';`

to `import type { Args, McpToolProperty } from '../../types/mcpTool';`

**Comment by chrisneven** [comment]
Yes @Q16solver is right

```
../../node_modules/@azure/functions/src/utils/toolProperties.ts:5:10 - error TS1484: 'McpToolProperty' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.

5 import { McpToolProperty } from '../../types/mcpTool';
```

Getting this with 4.8.2

**Comment by swapnil-nagar** [comment]
We’re preparing another release today (version 4.8.3) that will address this issue. I’ll provide an update once it’s available.

**Comment by swapnil-nagar** [comment]
Just did a release with that fix.

https://www.npmjs.com/package/@azure/functions/v/4.9.0

**Comment by jimmythomson** [comment]
Hi @swapnil-nagar - I'm seeing this issue manifesting slightly differently for me in 4.9.0:

<img width="1913" height="509" alt="Image" src="https://github.com/user-attachments/assets/0809fd38-8f2b-4635-974f-c0c14838d178" />

**Comment by fardarter** [comment]
I also have this issue
